language: java
jdk:
- oraclejdk8
- openjdk8
- openjdk9
- openjdk10
- openjdk11

notifications:
  email:
    recipients:
    - jlee@antwerkz.com
    on_success: change
    on_failure: always

services:
- mongodb